# Evaluation data: description, exploration, checks

```{r, warning=FALSE}
#| label: load-packages
#| code-summary: "load packages"


#devtools::install_github("rethinkpriorities/rp-r-package")
library(rethinkpriorities)

#devtools::install_github("rethinkpriorities/r-noodling-package")
library(rnoodling)

library(here)
source(here::here("code", "shared_packages_code.R"))
library(dplyr)
library(pacman)

p_load(santoku, lme4, huxtable, janitor, emmeans, sjPlot, sjmisc, ggeffects, ggrepel, likert, labelled, plotly, stringr, install=FALSE)

p_load(ggthemes, paletteer, ggridges, install=FALSE)

select <- dplyr::select

options(knitr.duplicate.label = "allow")

options(mc.cores = parallel::detectCores())
#rstan_options(auto_write = TRUE)
`

#library(hunspell)

#(brms)

#devtools::install_github("bergant/airtabler")
p_load(airtabler)

#remotes::install_github("rmcelreath/rethinking")
#library(rethinking)

```


## Input evaluation data

```{r}

base_id <- "appbPYEw9nURln7Qg"

# Set your Airtable API key
#Sys.setenv(AIRTABLE_API_KEY = "") 
#this should be set in my .Renviron file


# Read data from a specific view
evals <- air_get(base = "appbPYEw9nURln7Qg", "output_eval") 


```

```{r}
#| label: savedata
#| code-summary: "save the data for others to have access"

evals_pub <- evals %>% 
  dplyr::rename(stage_of_process = "stage of process/todo (from crucial_research 2)") %>%  
  mutate(stage_of_process = unlist(stage_of_process)) %>% 
  dplyr::filter(stage_of_process == "published") 

evals_pub %>% saveRDS(file = here("data", "evals.Rdata"))
evals_pub %>% write_csv(file = here("data", "evals.csv"))



```


<!-- need airtable API stuff -->

## Clean and impute 

- Unlist list rows

- Reconcile the uncertainty ratings and CIs (this is hard)
    

## Basic presentation

## Aggregation of expert opinion (modeling)

## Inter-rater reliability

## Decomposing variation, dimension reduction, simple linear models


