---
title: "Unjournal dashboard"
server: shiny
format: 
  html:
    page-layout: custom
---

```{r}
#| context: setup
#| include: false

library(dplyr)
library(lubridate)
library(here)

# names are display periods; values are relevant starting dates for data
periods <- c(
  "Ever"      = as.Date("1900-01-01"),
  "12 months" = today() - period(12, "months"),
  "6 months"  = today() - period(6, "months"),
  "1 month"   = today() - period(1, "months")
)

```

```{r}
#| panel: input

selectInput("period", "Period", names(periods))
```


```{r}
#| panel: fill
textOutput("papers_evaluated")
```



```{r}
#| context: server

descriptives <- reactiveValues(
  n_evals = 0L,
  n_papers = 0L,
  n_subfields = 0L
)

evals <- reactive({
  period_cutoff <- periods[[input$period]]
  evals_pub |> 
    filter(createdTime >= period_cutoff) 
})

n_evals <- reactive(nrow(evals()))
n_papers <- reactive(n_distinct(evals()$paper_abbrev))
n_subfields <- reactive({
  all_cats <- c(evals()$cat_1, evals()$cat_2, evals()$cat_3)
  n_distinct(all_cats)
})

output$papers_evaluated <- renderText({
  glue::glue("We ran {n_evals()} evaluations of {n_papers()} papers in
              {n_subfields()} distinct subfields.")  
})
  
```

```{r}
#| context: data
#| include: false

source(here("code/import-unjournal-data.R"))
# we now have evals_pub, all_papers_p, all_pub_records, and labels 

all_pub_dates <- all_pub_records |> select(id, createdTime)
rm(all_pub_records)

evals_pub <- left_join(evals_pub, all_pub_dates, 
                       by = join_by(crucial_rsx_id == id),
                       relationship = "many-to-one")

evals_pub <- evals_pub |> mutate(
  createdTime = as.POSIXct(createdTime)
)
```